/**
 * @xectec/tokens — Typed JavaScript Token Object
 *
 * Maps to the same values defined in tokens.css.
 * Use these in JavaScript contexts (e.g., charting libraries, canvas, email templates).
 *
 * Usage:
 *   import { tokens } from '@xectec/tokens';
 *   const chartColor = tokens.colors.primary[500];
 */

export const tokens = {
  colors: {
    primary: {
      50: "#eff6ff",
      100: "#dbeafe",
      200: "#bfdbfe",
      300: "#93c5fd",
      400: "#60a5fa",
      500: "#3b82f6",
      600: "#2563eb",
      700: "#1d4ed8",
      800: "#1e40af",
      900: "#1e3a8a",
      950: "#172554",
      DEFAULT: "#2563eb",
    },
    secondary: {
      50: "#eef2ff",
      100: "#e0e7ff",
      200: "#c7d2fe",
      300: "#a5b4fc",
      400: "#818cf8",
      500: "#6366f1",
      600: "#4f46e5",
      700: "#4338ca",
      800: "#3730a3",
      900: "#312e81",
      950: "#1e1b4b",
      DEFAULT: "#4f46e5",
    },
    success: {
      50: "#ecfdf5",
      100: "#d1fae5",
      200: "#a7f3d0",
      300: "#6ee7b7",
      400: "#34d399",
      500: "#10b981",
      600: "#059669",
      700: "#047857",
      800: "#065f46",
      900: "#064e3b",
      DEFAULT: "#059669",
    },
    warning: {
      50: "#fffbeb",
      100: "#fef3c7",
      200: "#fde68a",
      300: "#fcd34d",
      400: "#fbbf24",
      500: "#f59e0b",
      600: "#d97706",
      700: "#b45309",
      800: "#92400e",
      900: "#78350f",
      DEFAULT: "#f59e0b",
    },
    error: {
      50: "#fff1f2",
      100: "#ffe4e6",
      200: "#fecdd3",
      300: "#fda4af",
      400: "#fb7185",
      500: "#f43f5e",
      600: "#e11d48",
      700: "#be123c",
      800: "#9f1239",
      900: "#881337",
      DEFAULT: "#e11d48",
    },
    neutral: {
      0: "#ffffff",
      50: "#f8fafc",
      100: "#f1f5f9",
      200: "#e2e8f0",
      300: "#cbd5e1",
      400: "#94a3b8",
      500: "#64748b",
      600: "#475569",
      700: "#334155",
      800: "#1e293b",
      900: "#0f172a",
      950: "#020617",
    },
  },

  typography: {
    fontFamily: {
      sans: '"Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      mono: '"JetBrains Mono", "Fira Code", "Cascadia Code", Consolas, monospace',
    },
    fontSize: {
      "2xs": "0.625rem",
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
    },
    fontWeight: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
      extrabold: 800,
    },
    lineHeight: {
      tight: 1.25,
      snug: 1.375,
      normal: 1.5,
      relaxed: 1.625,
      loose: 2,
    },
    letterSpacing: {
      tight: "-0.025em",
      normal: "0em",
      wide: "0.025em",
      wider: "0.05em",
      widest: "0.1em",
    },
  },

  spacing: {
    0: "0",
    px: "1px",
    "0.5": "0.125rem",
    1: "0.25rem",
    "1.5": "0.375rem",
    2: "0.5rem",
    "2.5": "0.625rem",
    3: "0.75rem",
    4: "1rem",
    5: "1.25rem",
    6: "1.5rem",
    7: "1.75rem",
    8: "2rem",
    10: "2.5rem",
    12: "3rem",
    16: "4rem",
    20: "5rem",
    24: "6rem",
    // Named aliases
    xs: "0.5rem",
    sm: "0.75rem",
    md: "1rem",
    lg: "1.5rem",
    xl: "2rem",
    "2xl": "3rem",
  },

  radius: {
    none: "0",
    xs: "0.125rem",
    sm: "0.25rem",
    md: "0.375rem",
    lg: "0.5rem",
    xl: "0.75rem",
    "2xl": "1rem",
    "3xl": "1.5rem",
    full: "9999px",
  },

  shadows: {
    none: "none",
    xs: "0 1px 2px 0 rgba(0, 0, 0, 0.05)",
    sm: "0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.1)",
    md: "0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)",
    lg: "0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -4px rgba(0, 0, 0, 0.1)",
    xl: "0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 8px 10px -6px rgba(0, 0, 0, 0.1)",
    "2xl": "0 25px 50px -12px rgba(0, 0, 0, 0.25)",
    inner: "inset 0 2px 4px 0 rgba(0, 0, 0, 0.05)",
  },

  zIndex: {
    below: -1,
    base: 0,
    raised: 10,
    dropdown: 100,
    sticky: 200,
    overlay: 300,
    modal: 400,
    popover: 500,
    toast: 600,
    tooltip: 700,
  },

  transitions: {
    fast: "100ms ease",
    base: "150ms ease",
    slow: "300ms ease",
    spring: "300ms cubic-bezier(0.34, 1.56, 0.64, 1)",
  },

  components: {
    button: {
      radius: "var(--radius-button)",
      fontWeight: "var(--font-weight-button)",
      transition: "var(--transition-button)",
      spacing: {
        paddingX: {
          sm: "var(--spacing-button-padding-x-sm)",
          md: "var(--spacing-button-padding-x-md)",
          lg: "var(--spacing-button-padding-x-lg)",
        },
        paddingY: {
          sm: "var(--spacing-button-padding-y-sm)",
          md: "var(--spacing-button-padding-y-md)",
          lg: "var(--spacing-button-padding-y-lg)",
        },
        gap: "var(--spacing-button-gap)",
        marginX: "var(--spacing-button-margin-x)",
        marginY: "var(--spacing-button-margin-y)",
      },
      primary: {
        bg: "var(--color-button-primary-bg)",
        bgHover: "var(--color-button-primary-bg-hover)",
        bgActive: "var(--color-button-primary-bg-active)",
        text: "var(--color-button-primary-text)",
        border: "var(--color-button-primary-border)",
      },
      secondary: {
        bg: "var(--color-button-secondary-bg)",
        bgHover: "var(--color-button-secondary-bg-hover)",
        bgActive: "var(--color-button-secondary-bg-active)",
        text: "var(--color-button-secondary-text)",
        border: "var(--color-button-secondary-border)",
      },
      outline: {
        bg: "var(--color-button-outline-bg)",
        bgHover: "var(--color-button-outline-bg-hover)",
        bgActive: "var(--color-button-outline-bg-active)",
        text: "var(--color-button-outline-text)",
        border: "var(--color-button-outline-border)",
      },
      ghost: {
        bg: "var(--color-button-ghost-bg)",
        bgHover: "var(--color-button-ghost-bg-hover)",
        bgActive: "var(--color-button-ghost-bg-active)",
        text: "var(--color-button-ghost-text)",
        border: "var(--color-button-ghost-border)",
      },
      danger: {
        bg: "var(--color-button-danger-bg)",
        bgHover: "var(--color-button-danger-bg-hover)",
        bgActive: "var(--color-button-danger-bg-active)",
        text: "var(--color-button-danger-text)",
        border: "var(--color-button-danger-border)",
      },
      disabled: {
        bg: "var(--color-button-disabled-bg)",
        text: "var(--color-button-disabled-text)",
        border: "var(--color-button-disabled-border)",
      },
    },
    input: {
      radius: "var(--radius-input)",
      spacing: {
        paddingX: {
          sm: "var(--spacing-input-padding-x-sm)",
          md: "var(--spacing-input-padding-x-md)",
          lg: "var(--spacing-input-padding-x-lg)",
        },
        paddingY: {
          sm: "var(--spacing-input-padding-y-sm)",
          md: "var(--spacing-input-padding-y-md)",
          lg: "var(--spacing-input-padding-y-lg)",
        },
        gap: "var(--spacing-input-gap)",
      },
      bg: "var(--color-input-bg)",
      text: "var(--color-input-text)",
      placeholder: "var(--color-input-placeholder)",
      border: "var(--color-input-border)",
      borderHover: "var(--color-input-border-hover)",
      borderFocus: "var(--color-input-border-focus)",
      focusRing: "var(--color-input-focus-ring)",
      disabledBg: "var(--color-input-disabled-bg)",
      disabledText: "var(--color-input-disabled-text)",
      disabledBorder: "var(--color-input-disabled-border)",
      success: {
        border: "var(--color-input-success-border)",
        focusRing: "var(--color-input-success-focus-ring)",
      },
      error: {
        border: "var(--color-input-error-border)",
        focusRing: "var(--color-input-error-focus-ring)",
      },
    },
    card: {
      radius: "var(--radius-card)",
      spacing: {
        padding: {
          sm: "var(--spacing-card-padding-sm)",
          md: "var(--spacing-card-padding-md)",
          lg: "var(--spacing-card-padding-lg)",
        },
        gap: "var(--spacing-card-gap)",
      },
      bg: "var(--color-card-bg)",
      border: "var(--color-card-border)",
      headerBorder: "var(--color-card-header-border)",
      footerBorder: "var(--color-card-footer-border)",
      shadow: {
        flat: "var(--shadow-card-flat)",
        raised: "var(--shadow-card-raised)",
        floating: "var(--shadow-card-floating)",
      },
    },
    modal: {
      radius: "var(--radius-modal)",
      spacing: {
        padding: {
          sm: "var(--spacing-modal-padding-sm)",
          md: "var(--spacing-modal-padding-md)",
          lg: "var(--spacing-modal-padding-lg)",
        },
        gap: "var(--spacing-modal-gap)",
      },
      bg: "var(--color-modal-bg)",
      border: "var(--color-modal-border)",
      headerBorder: "var(--color-modal-header-border)",
      footerBorder: "var(--color-modal-footer-border)",
      overlay: "var(--color-modal-overlay)",
      shadow: "var(--shadow-modal)",
    },
    toast: {
      radius: "var(--radius-toast)",
      shadow: "var(--shadow-toast)",
      spacing: {
        padding: "var(--spacing-toast-padding)",
        gap: "var(--spacing-toast-gap)",
      },
      info: {
        bg: "var(--color-toast-info-bg)",
        border: "var(--color-toast-info-border)",
        text: "var(--color-toast-info-text)",
        icon: "var(--color-toast-info-icon)",
      },
      success: {
        bg: "var(--color-toast-success-bg)",
        border: "var(--color-toast-success-border)",
        text: "var(--color-toast-success-text)",
        icon: "var(--color-toast-success-icon)",
      },
      warning: {
        bg: "var(--color-toast-warning-bg)",
        border: "var(--color-toast-warning-border)",
        text: "var(--color-toast-warning-text)",
        icon: "var(--color-toast-warning-icon)",
      },
      error: {
        bg: "var(--color-toast-error-bg)",
        border: "var(--color-toast-error-border)",
        text: "var(--color-toast-error-text)",
        icon: "var(--color-toast-error-icon)",
      },
    },
    sidebar: {
      width: "var(--width-sidebar)",
      widthCollapsed: "var(--width-sidebar-collapsed)",
      spacing: {
        padding: "var(--spacing-sidebar-padding)",
        gap: "var(--spacing-sidebar-gap)",
      },
      bg: "var(--color-sidebar-bg)",
      border: "var(--color-sidebar-border)",
      text: "var(--color-sidebar-text)",
      textActive: "var(--color-sidebar-text-active)",
      itemHover: "var(--color-sidebar-item-hover)",
      itemActive: "var(--color-sidebar-item-active)",
    },
    header: {
      height: "var(--height-header)",
      bg: "var(--color-header-bg)",
      border: "var(--color-header-border)",
    },
    scrollbar: {
      track: "var(--color-scrollbar-track)",
      thumb: "var(--color-scrollbar-thumb)",
      thumbHover: "var(--color-scrollbar-thumb-hover)",
    },
    badge: {
      radius: "var(--radius-badge)",
      default: {
        bg: "var(--color-badge-default-bg)",
        text: "var(--color-badge-default-text)",
        border: "var(--color-badge-default-border)",
      },
      success: {
        bg: "var(--color-badge-success-bg)",
        text: "var(--color-badge-success-text)",
        border: "var(--color-badge-success-border)",
      },
      warning: {
        bg: "var(--color-badge-warning-bg)",
        text: "var(--color-badge-warning-text)",
        border: "var(--color-badge-warning-border)",
      },
      error: {
        bg: "var(--color-badge-error-bg)",
        text: "var(--color-badge-error-text)",
        border: "var(--color-badge-error-border)",
      },
    },
    element: {
      padding: {
        xs: "var(--spacing-element-padding-xs)",
        sm: "var(--spacing-element-padding-sm)",
        md: "var(--spacing-element-padding-md)",
        lg: "var(--spacing-element-padding-lg)",
        xl: "var(--spacing-element-padding-xl)",
      },
      margin: {
        xs: "var(--spacing-element-margin-xs)",
        sm: "var(--spacing-element-margin-sm)",
        md: "var(--spacing-element-margin-md)",
        lg: "var(--spacing-element-margin-lg)",
        xl: "var(--spacing-element-margin-xl)",
      },
      gap: {
        xs: "var(--spacing-element-gap-xs)",
        sm: "var(--spacing-element-gap-sm)",
        md: "var(--spacing-element-gap-md)",
        lg: "var(--spacing-element-gap-lg)",
        xl: "var(--spacing-element-gap-xl)",
      },
    },
  },
} as const;

export type Tokens = typeof tokens;
export type ColorScale = typeof tokens.colors.primary;
export type SpacingScale = typeof tokens.spacing;
export type ComponentTokens = typeof tokens.components;
